### ISSUE TITLE
s3-trigger-image-processing lambda requires access to S3

### ISSUE THREAD

**Issue by Jonasmst** [markwest1972/smart-security-camera#1]
The role used for s3-trigger-image-processing lambda function also needs access to S3. The AmazonS3ReadOnlyAccess seems to work fine. 

Thanks for writing up this project!

**Comment by markwest1972** [comment]
You are more than welcome!  It's nice to see that someone is actually reading this stuff!

My lambda function has the following access:

1. An AWSLambdaRole Managed Role.
2. An inline Role as follows:

`{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "states:StartExecution"
            ],
            "Resource": [
                "*"
            ]
        }
    ]
}`

I haven't specified any S3 access and yet the Lambda Function runs fine.  Weird!

**Comment by markwest1972** [comment]
Thinking this through - I wonder if the answer lies in how the Lambda Function is called (as an S3 trigger).  Maybe it then "inherits" the S3 access due to the context in which it is called?

Can you explain what problem you are encountering?  I'd love to get to the bottom of this.

**Comment by markwest1972** [comment]
No further information was received.

**Comment by Jonasmst** [comment]
Hi, sorry I didn't see your response until now, and I'm afraid I don't recall the details about this issue.  I haven't been able to find it in the logs either, though I'm not familiar with AWS at all, the only experience I have with it is through this project. It had something to do with fetching files from S3. The lambda would get triggered upon upload, but wouldn't be able to access S3 without the role mentioned above. 

It works now, though, and sends me an email every time a bird lands on my balcony, hehe

**Comment by markwest1972** [comment]
Great!  And good to know that you got everything working :)
