### ISSUE TITLE
lambda function fails

### ISSUE THREAD

**Issue by phrozendice** [markwest1972/smart-security-camera#13]
This function fails with the following error message:

Error [InvalidParameterValue: Missing required header 'From'.].

Full error message:

"errorMessage": "Error in [nodemailer-send-notification].\r   Function input [{\n  \"Alert\": \"true\",\n  \"Labels\": [\n    {\n      \"Name\": \"Human\",\n      \"Confidence\": 99.26097106933594\n    },\n    {\n      \"Name\": \"People\",\n      \"Confidence\": 99.26097106933594\n    },\n    {\n      \"Name\": \"Person\",\n      \"Confidence\": 99.26097106933594\n    },\n    {\n      \"Name\": \"Female\",\n      \"Confidence\": 72.58753967285156\n    },\n    {\n      \"Name\": \"Girl\",\n      \"Confidence\": 72.58753967285156\n    },\n    {\n      \"Name\": \"Woman\",\n      \"Confidence\": 72.58753967285156\n    },\n    {\n      \"Name\": \"Dimples\",\n      \"Confidence\": 71.27963256835938\n    },\n    {\n      \"Name\": \"Face\",\n      \"Confidence\": 71.27963256835938\n    },\n    {\n      \"Name\": \"Bling\",\n      \"Confidence\": 53.77670669555664\n    },\n    {\n      \"Name\": \"Jewelry\",\n      \"Confidence\": 53.77670669555664\n    },\n    {\n      \"Name\": \"Ornament\",\n      \"Confidence\": 53.77670669555664\n    },\n    {\n      \"Name\": \"Glasses\",\n      \"Confidence\": 52.02589797973633\n    },\n    {\n      \"Name\": \"Leisure Activities\",\n      \"Confidence\": 50.84391403198242\n    },\n    {\n      \"Name\": \"Sunglasses\",\n      \"Confidence\": 50.83937072753906\n    }\n  ],\n  \"OrientationCorrection\": \"ROTATE_0\",\n  \"bucket\": \"blahblah\",\n  \"key\": \"upload/0H2A8407.jpg\"\n}].\r   Error [InvalidParameterValue: Missing required header 'From'.]."

**Comment by markwest1972** [comment]
Can you please check that you have set the environment variables as defined [here](https://github.com/markwest1972/smart-security-camera/tree/master/aws-lambda-functions/nodejs/nodemailer-send-notification).

**Comment by phrozendice** [comment]
You are right Mark, my env variables were wrong, it works like a charm.

**Comment by markwest1972** [comment]
@phrozendice Great!
