### ISSUE TITLE
Node 6.10 EOL

### ISSUE THREAD

**Issue by mattncsu** [markwest1972/smart-security-camera#15]
Mark,

I know you aren't actively supporting this anymore, but do you know if the node.js code you wrote is compatible with 8.10?  Can I just change the runtime of the lamda functions in the AWS console from 6.10 to 8.10? 

Thanks,

Matt

**Comment by markwest1972** [comment]
I have idea. Give it a try :)

**Comment by markwest1972** [comment]
Meant to say I have *no* idea. Sorry about that :)

**Comment by mattncsu** [comment]
No problem! I was hesitant as I'm not familiar with node.js and wasn't home to do a proper test. Everything seems to be working fine on 8.10 (as in, i still get emails where  rekognition says with 99% confidence that my driveway is a basketball court)

**Comment by markwest1972** [comment]
Awesome :)
